name: base
dependencies:
  - matplotlib=3.1.1=py36_1
  - matplotlib-base=3.1.1=py36h3a684a6_1
  - numpy=1.16.2=py36h926163e_0
  - numpy-base=1.16.2=py36ha711998_0
  - scikit-learn=0.20.3=py36hebd9d1a_0
  - scipy=1.2.1=py36h1a1e112_0
  - seaborn=0.9.0=py36_0
  - pip:
    - astropy==3.1.2
    - beautifulsoup4==4.7.1
    - cdflib==0.3.9
    - heliopy==0.7.0
    - heliosat==0.2.2
    - predstorm==0.1
    - pyqt5==5.12.1
    - pyqt5-sip==4.19.15
    - spacepy==0.2.0
    - sunpy==1.0.1

